Rails/config/routes.rb
Rails.application.routes.draw do
  resources :vias_engativas
  resources :spatials
  resources :sites
  resources :streets
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root to: "pages#index"
  #resources :users, only:[:index]

  resources :typeincidents
  resources :roles
  resources :users
  resources :incidents
  resources :registries

  
end

Rails/app/models/vias_engativa.rb
class ViasEngativa < ApplicationRecord
end

Rails/app/controllers/vias_engativas_controller.rb
class ViasEngativasController < ApplicationController
  before_action :set_vias_engativa, only: [:show, :edit, :update, :destroy]

  # GET /vias_engativas
  # GET /vias_engativas.json
  def index
    #@vias_engativas = ViasEngativa.all
    query = "SELECT ST_X((dp).geom) AS lon, ST_Y((dp).geom) AS lat FROM (SELECT ST_DumpPoints(geom) AS dp from vias_engativas) AS qr"
    @vias_engativas = ActiveRecord::Base.connection.execute(query)
    render json: {data:@vias_engativas},status: :ok 
  end

  # GET /vias_engativas/1
  # GET /vias_engativas/1.json
  def show
  end

  # GET /vias_engativas/new
  def new
    @vias_engativa = ViasEngativa.new
  end

  # GET /vias_engativas/1/edit
  def edit
  end

  # POST /vias_engativas
  # POST /vias_engativas.json
  def create
    @vias_engativa = ViasEngativa.new(vias_engativa_params)

    respond_to do |format|
      if @vias_engativa.save
        format.html { redirect_to @vias_engativa, notice: 'Vias engativa was successfully created.' }
        format.json { render :show, status: :created, location: @vias_engativa }
      else
        format.html { render :new }
        format.json { render json: @vias_engativa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vias_engativas/1
  # PATCH/PUT /vias_engativas/1.json
  def update
    respond_to do |format|
      if @vias_engativa.update(vias_engativa_params)
        format.html { redirect_to @vias_engativa, notice: 'Vias engativa was successfully updated.' }
        format.json { render :show, status: :ok, location: @vias_engativa }
      else
        format.html { render :edit }
        format.json { render json: @vias_engativa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vias_engativas/1
  # DELETE /vias_engativas/1.json
  def destroy
    @vias_engativa.destroy
    respond_to do |format|
      format.html { redirect_to vias_engativas_url, notice: 'Vias engativa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vias_engativa
      @vias_engativa = ViasEngativa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vias_engativa_params
      params.require(:vias_engativa).permit(:mviccalzadad)
    end
end

Rails/app/helpers/vias_engativas_helper.rb
module ViasEngativasHelper
end

Rails/app/views/vias_engativas/_form.html.erb
<%= form_with(model: vias_engativa, local: true) do |form| %>
  <% if vias_engativa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vias_engativa.errors.count, "error") %> prohibited this vias_engativa from being saved:</h2>

      <ul>
      <% vias_engativa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mviccalzadad %>
    <%= form.number_field :mviccalzadad %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Rails/app/views/vias_engativas/edit.html.erb
<h1>Editing Vias Engativa</h1>

<%= render 'form', vias_engativa: @vias_engativa %>

<%= link_to 'Show', @vias_engativa %> |
<%= link_to 'Back', vias_engativas_path %>

Rails/app/views/vias_engativas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vias Engativas</h1>

<table>
  <thead>
    <tr>
      <th>Mviccalzadad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vias_engativas.each do |vias_engativa| %>
      <tr>
        <td><%= vias_engativa.mviccalzadad %></td>
        <td><%= link_to 'Show', vias_engativa %></td>
        <td><%= link_to 'Edit', edit_vias_engativa_path(vias_engativa) %></td>
        <td><%= link_to 'Destroy', vias_engativa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vias Engativa', new_vias_engativa_path %>

Rails/app/views/vias_engativas/new.html.erb
<h1>New Vias Engativa</h1>

<%= render 'form', vias_engativa: @vias_engativa %>

<%= link_to 'Back', vias_engativas_path %>

Rails/app/views/vias_engativas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mviccalzadad:</strong>
  <%= @vias_engativa.mviccalzadad %>
</p>

<%= link_to 'Edit', edit_vias_engativa_path(@vias_engativa) %> |
<%= link_to 'Back', vias_engativas_path %>