Rails/config/routes.rb
Rails.application.routes.draw do
  resources :vias_engativas
  resources :spatials
  resources :sites
  resources :streets
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root to: "pages#index"
  #resources :users, only:[:index]

  resources :typeincidents
  resources :roles
  resources :users
  resources :incidents
  resources :registries

  
end

Rails/app/models/street.rb
class Street < ApplicationRecord
end

Rails/app/controllers/streets_controller.rb
class StreetsController < ApplicationController
  before_action :set_street, only: [:show, :edit, :update, :destroy]

  # GET /streets
  # GET /streets.json
  def index
    @streets = Street.all
  end

  # GET /streets/1
  # GET /streets/1.json
  def show
  end

  # GET /streets/new
  def new
    @street = Street.new
  end

  # GET /streets/1/edit
  def edit
  end

  # POST /streets
  # POST /streets.json
  def create
    @street = Street.new(street_params)

    respond_to do |format|
      if @street.save
        format.html { redirect_to @street, notice: 'Street was successfully created.' }
        format.json { render :show, status: :created, location: @street }
      else
        format.html { render :new }
        format.json { render json: @street.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streets/1
  # PATCH/PUT /streets/1.json
  def update
    respond_to do |format|
      if @street.update(street_params)
        format.html { redirect_to @street, notice: 'Street was successfully updated.' }
        format.json { render :show, status: :ok, location: @street }
      else
        format.html { render :edit }
        format.json { render json: @street.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streets/1
  # DELETE /streets/1.json
  def destroy
    @street.destroy
    respond_to do |format|
      format.html { redirect_to streets_url, notice: 'Street was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_street
      @street = Street.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def street_params
      params.require(:street).permit(:mviccalzad, :mviccat, :mvitcla)
    end
end

Rails/app/helpers/streets_helper.rb
module StreetsHelper
end

Rails/app/views/streets/_form.html.erb
<%= form_with(model: street, local: true) do |form| %>
  <% if street.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(street.errors.count, "error") %> prohibited this street from being saved:</h2>

      <ul>
      <% street.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mviccalzad %>
    <%= form.number_field :mviccalzad %>
  </div>

  <div class="field">
    <%= form.label :mviccat %>
    <%= form.text_area :mviccat %>
  </div>

  <div class="field">
    <%= form.label :mvitcla %>
    <%= form.number_field :mvitcla %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Rails/app/views/streets/edit.html.erb
<h1>Editing Street</h1>

<%= render 'form', street: @street %>

<%= link_to 'Show', @street %> |
<%= link_to 'Back', streets_path %>

Rails/app/views/streets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Streets</h1>

<table>
  <thead>
    <tr>
      <th>Mviccalzad</th>
      <th>Mviccat</th>
      <th>Mvitcla</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @streets.each do |street| %>
      <tr>
        <td><%= street.mviccalzad %></td>
        <td><%= street.mviccat %></td>
        <td><%= street.mvitcla %></td>
        <td><%= link_to 'Show', street %></td>
        <td><%= link_to 'Edit', edit_street_path(street) %></td>
        <td><%= link_to 'Destroy', street, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Street', new_street_path %>

Rails/app/views/streets/new.html.erb
<h1>New Street</h1>

<%= render 'form', street: @street %>

<%= link_to 'Back', streets_path %>

Rails/app/views/streets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mviccalzad:</strong>
  <%= @street.mviccalzad %>
</p>

<p>
  <strong>Mviccat:</strong>
  <%= @street.mviccat %>
</p>

<p>
  <strong>Mvitcla:</strong>
  <%= @street.mvitcla %>
</p>

<%= link_to 'Edit', edit_street_path(@street) %> |
<%= link_to 'Back', streets_path %>